apiVersion: v1
kind: Pod
metadata:
  name: git-cli
  labels:
    app: git_cli
spec:
  volumes:
    - name: git-home
      hostPath:
        path: /cli_homes/git_home
    - name: git-projects-home
      hostPath:
        path: /projects_home
  containers:
    - name: git-cli
      image: localhost/git_cli:latest
      imagePullPolicy: Never
      command: ["tail"]
      args: ["-f", "/dev/null"]
      workingDir: /apps
      resources:
      volumeMounts:
        - name: git-home
          mountPath: /root
        - name: git-projects-home
          mountPath: /apps
