apiVersion: v1
kind: Service
metadata:
  name: gitea-app
spec:
  type: NodePort
  selector:
    app: gitea_server
  ports:
  - port: 22
    name: ssh-port
    targetPort: gitea-ssh-port
    nodePort: 30022
  - port: 80
    name: http-port
    targetPort: gitea-http-port
    nodePort: 30080
