apiVersion: v1
kind: Pod
metadata:
  name: gitea-app
  labels:
    app: gitea_server
spec:
  volumes:
    - name: gitea-data
      hostPath:
        path: /storage_homes/gitea/data
    - name: gitea-config
      hostPath:
        path: /storage_homes/gitea/config
    - name: gitea-timezone
      hostPath:
        path: /etc/timezone
    - name: gitea-localtime
      hostPath:
        path: /etc/localtime
  containers:
    - name: gitea-server
      image: docker.io/gitea/gitea:1.24-rootless
      imagePullPolicy: Never
      resources:
      volumeMounts:
        - name: gitea-data
          mountPath: /var/lib/gitea
        - name: gitea-config
          mountPath: /etc/gitea
        - name: gitea-timezone
          mountPath: /etc/timezone
        - name: gitea-localtime
          mountPath: /etc/localtime
      ports:
        - containerPort: 2222
          name: gitea-ssh-port
        - containerPort: 3000
          name: gitea-http-port
