apiVersion: v1
kind: Pod
metadata:
  name: gitlab-app
  labels:
    app: gitlab_server
spec:
  volumes:
    - name: gitlab-config
      hostPath:
        path: /storage_homes/gitlab/config
    - name: gitlab-logs
      hostPath:
        path: /storage_homes/gitlab/logs
    - name: gitlab-data
      hostPath:
        path: /storage_homes/gitlab/data
  containers:
    - name: gitlab-server
      image: docker.io/gitlab/gitlab-ce:17.11.5-ce.0
      imagePullPolicy: Never
      resources:
      volumeMounts:
        - name: gitlab-config
          mountPath: /etc/gitlab
        - name: gitlab-logs
          mountPath: /var/log/gitlab
        - name: gitlab-data
          mountPath: /var/opt/gitlab
      ports:
        - containerPort: 22
          name: glab-ssh-port
        - containerPort: 80
          name: glab-http-port
        - containerPort: 443
          name: glab-https-port
