kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: rust-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30022
    hostPort: 30022
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30443
    hostPort: 30443
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  extraMounts:
  - hostPath: ./cli_homes
    containerPath: /cli_homes
  - hostPath: ./storage_homes
    containerPath: /storage_homes
  - hostPath: ./projects_home
    containerPath: /projects_home
