apiVersion: v1
kind: Service
metadata:
  name: sonarqube-server
spec:
  type: NodePort
  selector:
    app: sonarqube_server
  ports:
  - port: 9000
    name: http-port
    targetPort: sqube-http-port
    nodePort: 31000
